version: '1.0'
name: linux-build
displayName: Linux Build
triggers:
  push:
    - matchType: PRECISE
      branch: main
    - matchType: PRECISE
      branch: master
  pullRequest:
    - matchType: PRECISE
      targetBranch: main
    - matchType: PRECISE
      targetBranch: master

stages:
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor:
      type: docker
      image: ubuntu:22.04
    steps:
      - step: shell@1
        name: checkout
        displayName: 检出代码
        script:
          - git clone $GITEE_REPO_URL --branch $GITEE_BRANCH --depth 1 .

      - step: shell@1
        name: install-system-deps
        displayName: 安装系统依赖
        script:
          - apt-get update
          - apt-get install -y build-essential cmake git curl zip unzip tar pkg-config
          - apt-get install -y libgtk-3-dev autoconf autoconf-archive automake libtool libltdl-dev

      - step: shell@1
        name: setup-vcpkg
        displayName: 设置 vcpkg
        script:
          - git clone https://github.com/microsoft/vcpkg.git
          - ./vcpkg/bootstrap-vcpkg.sh

      - step: shell@1
        name: install-deps
        displayName: 安装依赖
        script:
          - ./vcpkg/vcpkg install wxwidgets:x64-linux nlohmann-json:x64-linux

      - step: shell@1
        name: configure
        displayName: 配置 CMake
        script:
          - cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DCMAKE_BUILD_TYPE=Release

      - step: shell@1
        name: build
        displayName: 构建项目
        script:
          - cmake --build build --config Release

      - step: publish@1
        name: upload-artifact
        displayName: 上传构建产物
        artifact: MTC-Linux-Release
        source: bin/
